version: "3.9"

services:
  stripe-cli:
    image: stripe/stripe-cli
    network_mode: host
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to localhost:8000/webhooks/stripe/"
    env_file:
      - .env.prod

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "gunicorn tyres_shop.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    container_name: shop
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=tyres_shop.settings.production
    env_file:
      - .env.prod
    entrypoint: ./ep.prod.sh

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - app

volumes:
  db_data:
  static_volume:
  media_volume:
