version: "3.9"

services:
  stripe-cli:
    image: stripe/stripe-cli
    network_mode: host
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to localhost:8000/webhooks/stripe/"
    env_file:
      - .env

  app:
    build: ./
    container_name: shop
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=tyres_shop.settings.local
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  static_volume:
  media_volume:
  postgres_data:
