# Generated by Django 4.2.2 on 2023-08-07 12:22

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('stripe_product_price_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'out stock'), (1, 'in stock'), (2, 'running out'), (3, 'coming soon')], default=0)),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Stock quantity')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('et', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diameter', models.PositiveSmallIntegerField()),
                ('pcd', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Alloy'), (2, 'Steel')])),
                ('dia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'ordering': ['-updated', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('stripe_product_price_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'out stock'), (1, 'in stock'), (2, 'running out'), (3, 'coming soon')], default=0)),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Stock quantity')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[(1, 'Motorcycle'), (2, 'Car'), (3, 'Truck'), (4, 'Special transports')], verbose_name='Vehicle type')),
                ('profile', models.DecimalField(decimal_places=1, max_digits=4)),
                ('season', models.PositiveSmallIntegerField(choices=[(1, 'All'), (2, 'Summer'), (3, 'Winter')])),
                ('diameter', models.CharField(max_length=5)),
                ('width', models.PositiveSmallIntegerField()),
                ('load_index', models.PositiveSmallIntegerField(blank=True)),
                ('speed_index', models.CharField(blank=True, max_length=3)),
                ('spikes', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'ordering': ['-updated', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('tyre', 'wheel')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/assets/images/errors-images/no-image.png', upload_to=shop.models.user_directory_path)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='shop_galler_content_7f0cc2_idx')],
            },
        ),
    ]
