# Generated by Django 4.2.2 on 2023-08-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wheel',
            options={},
        ),
        migrations.AlterField(
            model_name='tyre',
            name='diameter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(1, 'All season'), (2, 'Summer'), (3, 'Winter')]),
        ),
    ]
