# Generated by Django 4.2.2 on 2023-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, unique=True, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name_uk',
            field=models.CharField(help_text='Required', max_length=255, null=True, unique=True, verbose_name='Type name'),
        ),
    ]
