# Generated by Django 4.2.2 on 2023-08-12 13:12

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_tyre_options_alter_wheel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static/assets/images/errors-images/no-image.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 400], upload_to=shop.models.user_directory_path),
        ),
    ]
