# Generated by Django 4.2.2 on 2023-11-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_producttype_name_alter_producttype_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product_type', 'name')},
        ),
    ]
