# Generated by Django 4.2.2 on 2023-11-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productspecificationvalue_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecificationvalue',
            unique_together={('specification', 'product')},
        ),
    ]
