# Generated by Django 4.2.2 on 2023-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productstatistic_alter_gallery_image_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wheel',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='pcd',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
