# Generated by Django 4.2.2 on 2023-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productspecificationvalue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(through='shop.ProductSpecificationValue', to='shop.productspecification'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='value_en',
            field=models.CharField(help_text='Product specification value (maximum of 255 characters', max_length=255, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='value_uk',
            field=models.CharField(help_text='Product specification value (maximum of 255 characters', max_length=255, null=True, verbose_name='value'),
        ),
    ]
