# Generated by Django 4.2.2 on 2023-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_tyre_stripe_product_price_id_alter_wheel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='load_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
