# Generated by Django 4.2.2 on 2023-11-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_specification_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecificationvalue',
            unique_together={('specification', 'product', 'value')},
        ),
    ]
