# Generated by Django 4.2.2 on 2023-11-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productspecificationvalue_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_is_main',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
