# Generated by Django 4.2.2 on 2023-10-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['email'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
