# Generated by Django 4.2.2 on 2023-10-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery_order_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
    ]
